# Generated by Django 5.2.9 on 2026-02-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_title', models.CharField(max_length=200)),
                ('main_title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('button_text', models.CharField(default='Shop Now', max_length=50)),
                ('button_link', models.URLField(blank=True)),
                ('background_image', models.ImageField(upload_to='discounts/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
