# Generated by Django 5.2.9 on 2026-02-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_aboutfeature_aboutimage_aboutwelcome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(help_text='مثل ri-customer-service-line', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.CharField(help_text='مثلاً section1 یا section2', max_length=50)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
